import React from "react";

export const adminStyles: Record<string, React.CSSProperties> = {
  page: {
    padding: 20,
  },
  // Контент админки занимает всю ширину экрана (как в разделе «Настройки генераций»).
  container: { width: "100%" },
  containerWide: { width: "100%" },
  containerXWide: { width: "100%" },
  // overflowX:auto — на мобиле 10 вкладок не влезают, даём горизонтальный скролл
  // вместо обрезки. На десктопе, если влезают, скролла нет.
  tabs: { display: "flex", gap: 0, marginBottom: 20, overflowX: "auto", scrollbarWidth: "none" },
  tab: {
    padding: "8px 14px",
    color: "#969696",
    textDecoration: "none",
    fontSize: 12,
    fontWeight: 500,
    borderBottom: "2px solid transparent",
    background: "transparent",
    fontFamily: "'Syne', sans-serif",
    whiteSpace: "nowrap",
    flexShrink: 0,
  },
  tabActive: { color: "#fff", borderBottom: "2px solid #f95bad" },
  card: {
    background: "#121212",
    border: "1px solid #313131",
    borderRadius: 8,
    padding: "24px 24px",
  },
  title: { color: "#fff", fontSize: 20, margin: "0 0 5px", fontWeight: 700 },
  subtitle: { color: "#848484", fontSize: 10, margin: "0 0 20px" },
  field: { marginBottom: 16 },
  row: { display: "flex", gap: 16, marginBottom: 16 },
  label: { display: "block", color: "#969696", fontSize: 10, marginBottom: 6, fontWeight: 500 },
  input: {
    width: "100%",
    background: "#1e1e1e",
    border: "1px solid #313131",
    borderRadius: 4,
    padding: "8px 12px",
    color: "#fff",
    fontSize: 12,
    fontWeight: 500,
    fontFamily: "'Syne', sans-serif",
    outline: "none",
    boxSizing: "border-box" as const,
  },
  button: {
    background: "linear-gradient(to right, #f95bad, #ff0084)",
    border: "none",
    color: "#fff",
    padding: "8px 14px",
    borderRadius: 4,
    fontSize: 12,
    fontWeight: 600,
    cursor: "pointer",
    fontFamily: "'Syne', sans-serif",
  },
  btnSecondary: {
    background: "#121212",
    border: "1px solid #313131",
    color: "#969696",
    padding: "8px 14px",
    borderRadius: 4,
    fontSize: 12,
    cursor: "pointer",
    fontFamily: "'Syne', sans-serif",
  },
  btnRow: { display: "flex", gap: 8, marginTop: 10 },
  btnSmall: {
    background: "#121212",
    border: "1px solid #313131",
    color: "#969696",
    padding: "4px 12px",
    borderRadius: 4,
    fontSize: 10,
    cursor: "pointer",
    fontFamily: "'Syne', sans-serif",
  },
  headerRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
    flexWrap: "wrap" as const,
    gap: 12,
  },
  link: { color: "#f95bad", textDecoration: "none", fontSize: 12 },
  error: {
    background: "rgba(227,100,102,0.15)",
    border: "1px solid #e36466",
    borderRadius: 4,
    padding: "8px 12px",
    color: "#e36466",
    fontSize: 10,
    marginBottom: 12,
  },
  success: {
    background: "rgba(193,240,170,0.15)",
    border: "1px solid #c1f0aa",
    borderRadius: 4,
    padding: "8px 12px",
    color: "#c1f0aa",
    fontSize: 10,
    marginBottom: 12,
  },
};
